version: '3.8'

networks:
  ecommerce-network:

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: borisdovo/mysql:1.0.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - ecommerce-network

  backend:
    container_name: backendNodejs
    build:
      context: ../backend
      dockerfile: ../backend/backend.Dockerfile
    image: borisdovo/backendnodejs:1.0.1
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    environment:
      MYSQL_HOST: db
    depends_on:
      - db

  frontend:
    container_name: frontendAngular
    build:
      context: ../frontend
      dockerfile: ../frontend/frontend.Dockerfile
    image: borisdovo/frontendangular:1.0.1
    ports:
      - "4200:80"
    networks:
      - ecommerce-network
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
